services:
  postgres:
    image: postgres:17.5
    restart: unless-stopped
    ports:
      - "5432:5432" # Пробросите порт на хост
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cloud_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d cloud_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: